### ISSUE TITLE
Panelize

### ISSUE THREAD

**Issue by bruktmoped** [SukkoPera/OpenC64Saver#2]
Great project! Thanks! I was trying to panelize this, but the provided gerbers are not recognized by gerber panelizer. I also tried to generate gerbers again inside Kicad, but still not recognized.

**Comment by SukkoPera** [comment]
Unfortunately I don't know how to do panelization at the moment. It would be good if someone took care of that and contributed panelized Gerber files.

I'm leaving this open so that it gets some visibility.

**Comment by rainisto** [comment]
[C64saver_V4_Panelized.zip](https://github.com/SukkoPera/OpenC64Saver/files/2555017/C64saver_V4_Panelized.zip)

Here is panelized version that I used when I ordered a set from jlcpcb (fitted 4 boards within the normal 10x10cm limit).

**Comment by SukkoPera** [comment]
Thanks Jonni, much appreciated! I will add your work to the release page.
