### ISSUE TITLE
bom parts list

### ISSUE THREAD

**Issue by ogg1e** [SukkoPera/OpenC64Saver#3]
It would be nice to have a parts list included in this design.

**Comment by SukkoPera** [comment]
This is coming very soon!

**Comment by SukkoPera** [comment]
Closed in V3 which was just released.

**Comment by ogg1e** [comment]
a typical BOM would also include the package type for each component as well.

**Comment by SukkoPera** [comment]
The BOM has the footprint, from which you can deduce the package type.

If you think a different format would be better, please provide steps for how to produce it in Kicad.

**Comment by ogg1e** [comment]
I'm sorry. I didn't see the csv in the release version. I was just looking at master and I didn't see a bom.
