### ISSUE TITLE
Unofficial v3 digikey bom is incorrect

### ISSUE THREAD

**Issue by MagerValp** [SukkoPera/OpenC64Saver#4]
The unofficial v3 digikey bom unfortunately contains two errors:

C1 is a 0.2pF instead of 0.2uF (e.g. [1276-2601-1-ND](https://www.digikey.com/products/en?keywords=1276-2601-1-ND))
R1 is 0.82 Ohm instead of 820 Ohm (e.g. [A130476CT-ND](https://www.digikey.com/products/en?keywords=A130476CT-ND))

**Comment by SukkoPera** [comment]
Could you please provide a fixed version?

And maybe could you also update it for V4? Only the resistors have changed, to their through-hole counterparts.

**Comment by MagerValp** [comment]
I can try fixing the two incorrect entries in V3, but it's really hard to find the right components on digikey...

[OpenC64Saver-3-updated_bom_digikey.csv.txt](https://github.com/SukkoPera/OpenC64Saver/files/2418535/OpenC64Saver-3-updated_bom_digikey.csv.txt)

**Comment by SukkoPera** [comment]
Thanks, will update ASAP.

**Comment by SukkoPera** [comment]
Updated, at last!
